--- #YAML:1.0
name:               Net-SMS-Massenversand
version:            0.02
abstract:           Send SMS via Massenversand.de
author:
    - Manuel Laux <laux@medicalrecall.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor::Fast:  0
    Crypt::SSLeay:        0
    LWP::UserAgent:       0
    Test::More:           0
    Unicode::String:      0
    URI:                  0
    URI::QueryParam:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
